export class Peea18ilvem {
    constructor(
        public _id?:string,
        public idContrato?:string,
        public fecha?:Date,
        public pregunta1?:any,
        public pregunta2?:any,
        public pregunta3?:any,
        public pregunta4?:any,
        public pregunta5?:any,
        public pregunta6?:any,
        public pregunta7?:any,
        public pregunta8?:any,
        public pregunta9?:any,
        public pregunta10?:any,
        public pregunta11?:any,
        public pregunta12?:any,
        public pregunta13?:any,
        public pregunta14?:any,
        public pregunta15?:any,
        public pregunta16?:any,
        public pregunta17?:any,
        public pregunta18?:any,
        public pregunta19?:any,
        public pregunta20?:any,
        public pregunta21?:any,
        public pregunta22?:any,
        public pregunta23?:any,
        public pregunta24?:any,
        public pregunta25?:any,
        public pregunta26?:any,
        public pregunta27?:any,
        public pregunta28?:any,
        public pregunta29?:any,
        public pregunta30?:any,
        public pregunta31?:any,
        public pregunta32?:any,
        public pregunta33?:any,
        public pregunta34?:any,
        public pregunta35?:any,
        public pregunta36?:any,
        public pregunta37?:any,
        public pregunta38?:any,
        public idEstudiante?:any,
        public addedUser?:any,
        public modifiedUser?:any
    ){}
}